### ISSUE TITLE
[Algorithm] 현재 사용하고 있는 알고리즘

### ISSUE THREAD

**Issue by LentoAssai** [DeveloperAcademy-POSTECH/MC2-Team16-Trit#35]
# O(n^2) (Sub Algorithm)
```swift

import Foundation

var myDictionary: [String : Int] = [:]

print("몇차까지 달렸나요?")
let n = Int(readLine()!)!

for i in 1...n {
    print("\(i)차 몇명인가요?")
    let numOfPerson = Int(readLine()!)!

    print("\(i)차 총 금액 입력")
    let totalPrice = Int(readLine()!)!

    let splittedPrice = totalPrice / numOfPerson


    print("\(i)차 정산자는 누구?")
    let leader = readLine()!


    // 정산자가 딕셔너리에 없는 경우 예외 처리 추가해야함

    print("\(i)차 참가자 이름 입력")
    for _ in 0..<numOfPerson {

        let name = readLine()!
        if let curPrice = myDictionary[name] {
            // 기존에 인원이 있는 상황
            if name == leader {
                // 정산자라면
                myDictionary.updateValue(curPrice + splittedPrice * (numOfPerson - 1), forKey: name)
            } else {
                // 참여자라면
                myDictionary.updateValue(curPrice - splittedPrice, forKey: name)
            }


        } else {
            // 새로 인원이 추가된 상황
            if name == leader {
                // 정산자라면
                myDictionary.updateValue(splittedPrice * (numOfPerson - 1), forKey: name)
            } else {
                // 참여자라면
                myDictionary.updateValue(-splittedPrice, forKey: name)
            }
        }

    }
}
print("총 딕셔너리 : ", myDictionary)




var givers: [String : Int] = myDictionary.filter { $0.value < 0 }


// givers의 value가 음수이므로 양수로 바꾸기
for key in givers.keys {
    givers[key]! *= -1
}


let takers = myDictionary.filter { $0.value > 0 }

print("그냥 givers : ", givers)
print("그냥 takers : ", takers)

var sortedGivers = givers.sorted { $0.value > $1.value } // value의 절댓값이 큰 순서로 정렬
var sortedTakers = takers.sorted { $0.value > $1.value } // value의 절댓값이 큰 순서로 정렬


print("정렬 givers : ", sortedGivers)
print("정렬 takers : ", sortedTakers)

// Giver Taker 분류 완료

// ------------------------------------------------------------------------------------
// ------------------------------------------------------------------------------------
// ------------------------------------------------------------------------------------
// ------------------------------------------------------------------------------------
// ------------------------------------------------------------------------------------

// 송금

var numOfSending = 0


var giverIndex = 0
let takerIndex = 0

mainLoop: while(!(sortedGivers.isEmpty || sortedTakers.isEmpty)) {
    print(numOfSending + 1, "번째입니다.")
    
    // 같은거 있는지 확인 후 처리 (완전 탐색 말고 다른거 없나?)
    for i in 0..<sortedGivers.count {
        for j in 0..<sortedTakers.count {
            if sortedGivers[i].value == sortedTakers[j].value {
                
                print("\(sortedGivers[i].key)가 \(sortedTakers[j].key)에게 \(sortedGivers[i].value)원을 주었습니다.")
                
                numOfSending += 1
                sortedGivers.remove(at: i)
                sortedTakers.remove(at: j)
                
                continue mainLoop
            }
        }
    }
    
    
    
    giverIndex = 0
    
    
    
    // Taker < Giver 이면 다음 Giver로 넘어가기
    while sortedGivers[giverIndex].value > sortedTakers[takerIndex].value {
        
        if giverIndex >= sortedGivers.count - 1 {
            giverIndex = 0
            break
        }
        
        giverIndex += 1
        
    }
    
    
    let givingMoney = sortedGivers[giverIndex].value
    let takingMoney = sortedTakers[takerIndex].value
    
    print("givingMoney : ", givingMoney, "takingMoney : ", takingMoney)
    
    
    if givingMoney < takingMoney {
        
        sortedTakers[takerIndex].value -= givingMoney
        print("\(sortedGivers[giverIndex].key)가 \(sortedTakers[takerIndex].key)에게 \(givingMoney)원을 주었습니다.")
        
        sortedGivers.remove(at: giverIndex)
        
        
    } else {
        // 끝까지 갔는데 없어서 맨 위로 돌아온 경우
        sortedGivers[giverIndex].value -= takingMoney
        print("\(sortedGivers[giverIndex].key)가 \(sortedTakers[takerIndex].key)에게 \(takingMoney)원을 주었습니다.")
        
        sortedTakers.remove(at: takerIndex)
        
    }
    
    numOfSending += 1
    
    print()
}

print()
print("총 송금 횟수 : ", numOfSending)


```

# O(n log n) (Main Algorithm)

```swift
import Foundation

func SplitBillAlgorithm() {
    var sendingCount = 0
    let members = getUserInput()
    
    var sortedGivers = extractGivers(members)
    var sortedTakers = extractTakers(members)
    
    while !(sortedGivers.isEmpty || sortedTakers.isEmpty) {
        // 같은거 처리부터 하면 완전 탐색을 해야해서 n^2으로 가야함
        // 정렬을 어차피 할거니까 정렬 후 같은거 처리하면 n logn으로 줄일 수 있음 (Jason 말씀해주신거)
        // 따라서 정렬을 먼저 하자
        
        // 정렬
        sortedGivers = descendingSort(sortedGivers)
        sortedTakers = descendingSort(sortedTakers)
        
        // 같은거 처리
        handleSamePrice(sortedGivers, sortedTakers, &sendingCount)
        
        // 큰거부터 처리
        sendingFunction(&sortedGivers, &sortedTakers, &sendingCount)
        
    }
    
    print("총 정산 횟수 : \(sendingCount)")
}


func getUserInput() -> [String : Double] {
    print("Payment 개수 입력 : ")
    let paymentCount = Int(readLine()!)!
    
    var members: [String : Double] = [:]
    
    for i in 1...paymentCount {
        
        print("\(i)차 참가 인원은 몇명인가요?")
        let numOfPerson = Int(readLine()!)!
        
        print("\(i)차 금액은 얼마인가요?")
        let totalPrice = Double(readLine()!)!
        let splittedPrice: Double = totalPrice / Double(numOfPerson)
        
        print("\(i)차 정산자는 누구인가요?")
        let leader = readLine()!
        
        print("\(i)차 참가자들을 입력하세요")
        for _ in 0..<numOfPerson {
            
            let name = readLine()!
            if let curPrice = members[name] {
                // 기존에 인원이 있는 상황
                if name == leader {
                    // 정산자라면
                    members.updateValue(curPrice + splittedPrice * Double(numOfPerson - 1), forKey: name)
                } else {
                    // 참여자라면
                    members.updateValue(curPrice - splittedPrice, forKey: name)
                }


            } else {
                // 새로 인원이 추가된 상황
                if name == leader {
                    // 정산자라면
                    members.updateValue(splittedPrice * Double(numOfPerson - 1), forKey: name)
                } else {
                    // 참여자라면
                    members.updateValue(-splittedPrice, forKey: name)
                }
            }
        }
    }
    
    return members
}

func extractGivers(_ members: [String : Double]) -> Array<(key: String, value: Double)> {
    return members.filter { $0.value < 0 }.map { ($0.key, -$0.value) }
}
func extractTakers(_ members: [String : Double]) -> Array<(key: String, value: Double)> {
    return members.filter { $0.value > 0 }
}


//Array<(key: String, value: Double)> 랑 Array<[String : Double]> 다른가보다?
func descendingSort(_ group: Array<(key: String, value: Double)>) -> Array<(key: String, value: Double)> {
    return group.sorted(by: { $0.value > $1.value })
}

func handleSamePrice(_ sortedGivers: [(key: String, value: Double)], _ sortedTakers: [(key: String, value: Double)], _ sendingCount: inout Int) {
    var i = 0
    var j = 0
    
    while i < sortedGivers.count && j < sortedTakers.count {
        if sortedGivers[i] == sortedTakers[j] {
            
            sendingMessage(from: sortedGivers[i].key, to: sortedTakers[j].key, amount: sortedGivers[i].value)
            i += 1
            sendingCount += 1
            
        } else if sortedGivers[i] < sortedTakers[j] {
            i += 1
        } else {
            j += 1
        }
    }
}

func sendingFunction(_ sortedGivers: inout [(key: String, value: Double)], _ sortedTakers: inout [(key: String, value: Double)], _ sendingCount: inout Int) {
    
    if sortedGivers[0].value < sortedTakers[0].value {
        
        sendingMessage(from: sortedGivers[0].key, to: sortedTakers[0].key, amount: sortedGivers[0].value)
        sortedTakers[0].value -= sortedGivers[0].value
        sortedGivers.remove(at: 0)
        
    } else {
        
        sendingMessage(from: sortedGivers[0].key, to: sortedTakers[0].key, amount: sortedTakers[0].value)
        sortedGivers[0].value -= sortedTakers[0].value
        sortedTakers.remove(at: 0)
        
    }
    
    sendingCount += 1
}

func sendingMessage(from: String, to: String, amount: Double) {
    print("\(from)이(가) \(to)에게 \(amount)원을 주었습니다.")
}


SplitBillAlgorithm()
```

최소 송금횟수를 목표로 했지만 완벽하지는 않습니다.

## Todo
- [x] main 알고리즘 입력 방법 수정하기
- [x] 입력 Int에서 Double로 수정하기
- [ ] 절삭 함수 추가하기
- [ ] 왜 결과 금액이 나왔는지 과정을 보여주는 시각화 가능하게 다시 생각해보기
- [ ] 최소 송금횟수 목표로 다시 생각해보기
- [ ] 송금횟수 골고루 돌아가도록 하기
