### ISSUE TITLE
[TASK-FIX] Fix/Charlie/Chore : Fixing UI (1)

### ISSUE THREAD

**Issue by LentoAssai** [DeveloperAcademy-POSTECH/MC2-Team16-Trit#43]
# 작업 내용
- [X] UserInfoView, HomeView에서 slideOverCard, AddSpaceView, AddCardTitleView, AddCardDecoView에서 계좌번호 입력 시, EditSpaceNameView, EditProfileView, EditAccountView에서 키보드 타입 정해주기
- [X] UserInfoView, HomeView에서 slideOverCard, AddSpaceView, AddCardTitleView, AddCardDecoView에서 계좌번호 입력 시, EditSpaceNameView, EditProfileView, EditAccountView에서 바탕 누르면 키보드 내려가게 작업
- [X] UserInfoView, TermView 다음 버튼 공용 컴포넌트로 바꾸기
- [X] UserInfoView, TermView 다음 버튼 padding(.bottom) 주기
- [X] UserInfoView 제목 빼고 입력받는 TextField들 ScrollView로 감싸기
- [X] TermView "돈워리 이용을 위해 약관에 동의해 주세요." 폰트 키우기
- [X] TermView 전체 padding(.horizontal, 15) 추가하기
- [X] AccountTextField의 x버튼 UnderlineTextField와 같이 크기 좀 더 키우고 padding 추가하기
- [X] SpaceMainCardView의 clicked, onTapGesture 삭제, SpaceMainView의 각 카드에 onTapGesuture를 추가
- [X] toolbar에 추가한 뒤로가기 버튼에 padding(.horizontal) 적용하기

# 상세 작업 내용
### UIApplicationExtension 추가
- Extension 디렉토리에 키보드 dismiss를 위한 UIApplicationExtension 추가

### UserInfoView
- AccountTextField( ) 주석 해제 및 account, bank 변수 선언 후 전달
- 닉네임, 예금주 입력 TextField의 keyboardType을 default로 적용
<br>

- isFocused 변수 선언 및 focused 모디파이어 추가, 버튼 클릭 시 isFocused에 false를 대입하여 키보드 비활성화
- onAppear를 추가하여 키보드 내리기 구현
<br>

- 다음 버튼을 공용 컴포넌트인 SmallButton으로 구현
- 다음 버튼에 padding(.bottom) 추가
- TextField들 ScrollView로 감싸기
- toolbar 뒤로가기 버튼에 padding(.horizontal) 추가

### AccountTextField

- 계좌번호 입력 TextField의 keyboardType을 decimalPad로 적용
- 13으로 설정된 font modifier 삭제
- 계좌번호 입력 HStack의 width를 350에서 335로 수정

### ChooseBankSheet
- 직접입력 TextField의 keyboardType을 default로 적용

### HomeView
- slideOverCard에서 스페이스 ID 입력 TextField의 keyboardType을 asciiCapable로 적용
<br>

- isFocused 변수 선언 및 focused 모디파이어 추가, 버튼 클릭 시 isFocused에 false를 대입하여 키보드 비활성화
- onAppear를 추가하여 키보드 내리기 구현

### AddSpaceView
- 스페이스 이름 입력 TextField의 keyboardType을 default로 적용
<br>

- isFocused 변수 선언 및 focused 모디파이어 추가, 버튼 클릭 시 isFocused에 false를 대입하여 키보드 비활성화
- onAppear를 추가하여 키보드 내리기 구현

### AddCardTitleView
- 이전에 사용하던 NavigationLink의 주석 제거
- 정산 항목 입력 TextField의 keyboardType을 default로 적용
<br>

- isFocused 변수 선언 및 focused 모디파이어 추가, 버튼 클릭 시 isFocused에 false를 대입하여 키보드 비활성화
- onAppear를 추가하여 키보드 내리기 구현

### AddCardDecoView
- holder (예금주명) 변수 추가 및 AccountTextField의 하드코딩 수정
- accountBox의 예금주 입력 TextField의 keyboardType default로 적용
- accountBox의 계좌번호 입력 TextField의 keyboardType을 decimalPad로 적용
<br>

- isFocused 변수 선언 및 focused 모디파이어 추가, 버튼 클릭 시 isFocused에 false를 대입하여 키보드 비활성화
- onAppear를 추가하여 키보드 내리기 구현

### EditSpaceNameView
- 스페이스 이름 수정 TextField의 keyboardType을 default로 적용
<br>

- isFocused 변수 선언 및 focused 모디파이어 추가, 버튼 클릭 시 isFocused에 false를 대입하여 키보드 비활성화
- onAppear를 추가하여 키보드 내리기 구현
- toolbar 뒤로가기 버튼에 폰트 삭제 및 padding(.horizontal) 추가

### EditProfileView
- UnderlineTextField 주석 해제
- selectedTag 변수 삭제
- name 변수 선언 및 UnderlineTextField에 전달
- 이름 입력 TextField의 keyboardType을 default로 적용
<br>

- isFocused 변수 선언 및 focused 모디파이어 추가, 버튼 클릭 시 isFocused에 false를 대입하여 키보드 비활성화
- onAppear를 추가하여 키보드 내리기 구현
- toolbar 뒤로가기 버튼에 padding(.horizontal) 추가

### EditAccountView
- selectedTag 변수 삭제
- holder, bank, account 변수 선언 및 TextField에 전달
- 예금주명 입력 TextField 주석 해제 및 keyboardType을 default로 적용
- 계좌정보 입력 TextField를 AccountTextField로 적용
<br>

- isFocused 변수 선언 및 focused 모디파이어 추가, 버튼 클릭 시 isFocused에 false를 대입하여 키보드 비활성화
- onAppear를 추가하여 키보드 내리기 구현
- toolbar 뒤로가기 버튼에 padding(.horizontal) 추가

### SpaceMainCardView
- clicked 변수, onTapGesture 제거

### SpaceMainView
- SpaceMainCardView에서 제거한 onTapGesture를 각 카드에 추가하여 isModalPresented에 true값 대입

### TermView
- "돈워리 이용을 위해 약관에 동의해 주세요." 폰트 23으로 설정
- padding(.horizontal, 15) 추가
- toolbar 뒤로가기 버튼에 padding(.horizontal) 추가
<br>

- 다음 버튼을 공용 컴포넌트인 SmallButton으로 구현
- 다음 버튼에 padding(.bottom) 추가
- toolbar 뒤로가기 버튼에 padding(.horizontal) 추가

### AlertView
- toolbar 뒤로가기 버튼에 padding(.horizontal) 추가

### ProfileView
- toolbar 뒤로가기 버튼에 padding(.horizontal) 추가

---

# Todo
- [ ] UserInfoView, AddSpaceView, AddCardTitleView, EditSpaceNameView, EditProfileView, EditAccountView에서 TextField활성화 시 다음, 확인 버튼도 같이 올라오게 하기
- [ ] 뒤로가기 스와이프로 가능하게 코드 작성하기
- [ ] isFocused가 있는 뷰에서 버튼 클릭 시 isFocused에 false를 대입하여 키보드 비활성화
- [ ] HomeView에서 검색 sheet가 올라왔을 때 TextField를 눌렀을 때 키보드가 올라오는거는 수정해야함
- [ ] UserInfoView, HomeView에서 slideOverCard, AddSpaceView, AddCardTitleView, AddCardDecoView에서 계좌번호 입력 시, EditSpaceNameView, EditProfileView, EditAccountView에서 적절한 입력만 제한받도록 하기 (닉네임 특수문자 제한, )
- [ ] 계좌번호 입력 시 은행에 따라 적절한 formatter에 변환하여 보여주기
- [ ] AddCardDecoView에서 계좌정보를 유저의 디폴트 계좌정보로 먼저 불러오기
- [ ] EditProfileView 확인 시 페이지 dismiss 추가하기
- [ ] TermView에서 버튼을  공용 컴포넌트로 바꾸기 (Avery 브랜치에 가서 수정해야 할듯)
- [ ] isFocused 변수가 굳이 필요 없을 수 있음. 상황보고 다시 삭제하기
