### ISSUE TITLE
[TASK-FIX] Fix/Charlie/Chore : Fixing UI (2)

### ISSUE THREAD

**Issue by LentoAssai** [DeveloperAcademy-POSTECH/MC2-Team16-Trit#45]
# 작업 내용
- [X] UserInfoView에서 뒤로가기 기능 제거
- [X] 뒤로가기 스와이프로 가능하게 코드 작성하기
- [ ] ChooseBankSheet 수정
- [x] UserInfoView, AddSpaceView, AddCardTitleView, EditSpaceNameView, EditProfileView, EditAccountView에서 TextField활성화 시 다음, 확인 버튼도 같이 올라오게 하기
- [ ] isFocused가 있는 뷰에서 버튼 클릭 시 isFocused에 false를 대입하여 키보드 비활성화
- [x] HomeView에서 검색 sheet가 올라왔을 때 TextField를 눌렀을 때 키보드가 올라오는거는 수정해야함
- [ ] UserInfoView, HomeView에서 slideOverCard, AddSpaceView, AddCardTitleView, AddCardDecoView에서 계좌번호 입력 시, EditSpaceNameView, EditProfileView, EditAccountView에서 적절한 입력만 제한받도록 하기 (닉네임 특수문자 제한, )
- [ ] 계좌번호 입력 시 은행에 따라 적절한 formatter에 변환하여 보여주기
- [ ] AddCardDecoView에서 계좌정보를 유저의 디폴트 계좌정보로 먼저 불러오기
- [x] EditProfileView 확인 시 페이지 dismiss 추가하기
- [ ] isFocused 변수가 굳이 필요 없을 수 있음. 상황보고 다시 삭제하기

# 상세 작업 내용

### ChooseBankSheet
- 은행 이미지를 아래와 같이 수정
```swift
Image(bank)
    .resizable()
    .scaledToFit()
    .cornerRadius(5)
    .frame(width: 30, height: 30)
    .background(RoundedRectangle(cornerRadius: 5)
    .stroke(Color.grayC5))
```

<br>

### UINavigationControllerExtension 추가
- Extension 디렉토리에 드래그를 이용한 뒤로가기를 위한 UINavigationControllerExtension 추가

<br>

### UserInfoView
- toolbar 제거하여 뒤로가기 버튼 삭제

<br>

### TermView
- 

<br>

### ProfileView
- 

<br>

### EditProfileView
- 확인 버튼 클릭 시 페이지 dismiss 추가

<br>

### EditAccountView
- 

<br>

### AlertView
- 

<br>

### AddSpaceView
- 

<br>

### EditSpaceNameView
- 

<br>

### AddCardTitleView
- 

<br>

### AddCardIconView
- 

<br>

### AddCardPriceView
-

<br>

### AddCardDecoView
- 

<br>

---

# Todo
- [ ] UserInfoView, SpaceMainView에서 스와이프 뒤로가기 기능 제거하기
- [ ] @Environment(\.presentingMode) var mode 를 @Environment(\.dismiss) var dismiss 로 바꾸고 self.mode.wrappedValue.dismiss( )를 그냥 dismiss( )로 바꾸기
- [ ] SpaceMainView, SpaceMainCardView에서 계좌번호 복사 시 팝업창 안나오는 이슈 해결하기
- [ ] 모든 다음, 확인 버튼들 비었으면 disable 시키고 비활성화일 때 색상도 바꾸기
1. EditNameView 에서 이름 입력 후 확인 눌렀을 때 키보드 안내려감, 패딩값 수정, 확인 눌렀을 때 뒤로 안가짐
2. EditAccountView에서 계좌 입력 후 확인 눌렀을 때 키보드 안내려감, 패딩값 수정, 확인 눌렀을 때 뒤로 안가짐
3. SpaceMainView, SpaceMainCardView에서 계좌 복사 버튼을 눌렀을 때 복사되었습니다 팝업창 안뜸
4. Profile View에서 프로필사진 클릭 시 수정 안됨
