### ISSUE TITLE
[TODO] UI Fix

### ISSUE THREAD

**Issue by LentoAssai** [DeveloperAcademy-POSTECH/MC2-Team16-Trit#54]
# 수정 후 체크박스에 체크하기
# PR을 올렸으면 풀 해달라고 단톡에 요청하기

페이지 별로 수정이 필요하거나 개선해야 할 점들에 대해 정리했습니다.

정리가 안되어 누락된 부분 또는 더 수정해야 할 부분들이 있을 수 있습니다.
해당 사항이 있으시면 언제든 공유해주시고 수정해주시면 감사하겠습니다.

각 페이지 옆에는 페이지를 만든 사람을 태그하였고, Todo list 옆에는 누가 맡을지를 태그하였습니다.
완료하시고 체크 눌러주시면 되겠습니다.
다들 너무 고생 많으시고 마지막까지 화이팅입니다!

### 모든 뷰
- [x] 버튼 disable 시 버튼 비활성화 (@LentoAssai )
- [x] 버튼 disable 시 색상 변경 (@LentoAssai ) (공용 컴포넌트 Large, Small button에 isDisable 추가함)
- [ ] 페이지 dismiss 변수 바꾸기 (@LentoAssai )
- [x] 복사하기 버튼을 좋은 레퍼런스를 참고하여 버튼 수정하기 (SF symbols의 doc.on.doc) 이후 찰리에게 말해주기 (@kimscastle )
- [x] 복사하기 기능 다시 넣기 (@LentoAssai ) (GiverDonCard Sheet 유스 수정 후 기능 넣기)
- [x] GiverDonCard새로운디자인적용 (@kimscastle )

### UnderlineTextField (@LentoAssai )
- [x] 글자수 제한 오른쪽으로 붙이기

### TermView (@LentoAssai )
- [ ] 약관 상세내용 추가하기 (@Asher3576 )
- [x] 약관 상세내용 폰트 수정하기 및 왼쪽 정렬로 바꾸기 (@Asher3576 )

### TermSheetView (@LentoAssai )
- [x] slideOverCard로 바꾸기 (@LentoAssai )
- [x] 좌우 패딩 추가하기 (@LentoAssai )
- [x] 시트 크기 조절할 수 있으면 조절하기 (3개만 동의하면 밑에 공간이 많이 남음) (@LentoAssai )
- [x] 확인 버튼 큰걸로 수정하기 (@LentoAssai )
- [x] 시트 라운드 줄 수 있으면 주기 (@LentoAssai )

### HomeView (@chaneeii )
- 프로필 이미지는 기본으로 하나 픽스. 나중에 몇개의 프리셋을 제공하여 선택할 수 있도록 하기
- [ ] 돈카드 시작 카드가 왼쪽이 붙는 이슈 해결하기. 우디에게 받아봐야 함. (@chaneeii )
- [x] 기본 프로필 이미지가 하나 필요함 (@Asher3576 )
- [x] 스페이스 최대 개수 제한 토스트 팝업 멘트 정해주기 (@Asher3576 )
- [ ] 스페이스 최대 개수가 5개임을 사용자에게 알려야 할 필요가 있음. 최대 개수일 때 스페이스를 생성하려고 할 때 토스트 팝업으로 안된다고 알림 주기 (@kimscastle )
- [x] 돈카드에 위로 스와이프해서 뭐시기 삭제하기 (@kimscastle )
- [x] 돈카드 라운드 적당히 더 주기 (@kimscastle )

### ProfileView (@chaneeii )
- [x] 내정보 오른쪽 위로 배치하기 (@Asher3576 )
- [x] 복사 기능 제거하기 (@Asher3576 )
- [x] 준비중 멘트 정하기 (@Asher3576 )
- [ ] 공지사항, 1대1 문의는 준비중입니다 팝업 구현하기 (@kimscastle )
- [x] 이용약관, 로그아웃, 회원탈퇴 기능 구현 (@Asher3576 )
- [x] 로그아웃, 회원탈퇴는 alert 주기 (@Asher3576 )

### SpaceMainView (@kyustudyo )
- 스페이스 나가기에는 조건이 필요함. 예를 들어 정산이 시작되었을 때 부터는 나가기가 안되도록 해야함. 다른 조건들이 더 있는지 고민해보기
- [x] ... 버튼 눌렀을 때 스페이스 나가기 버튼 (스페이스 화면에서 나가기가 아닌 스페이스에서 나가기) 추가 (@LentoAssai  )
- [x] 링크공유, 참석확인 버튼이 다른 앱에서 키보드를 활성화 시키고 돌아왔을 때 중간에 올라와있는 버그 해결하기 (ignoreSafeArea 해보기) (@LentoAssai )
- [x] 정산추가 버튼 아래쪽에 Spacer( ) 등의 방법으로 공간을 더 주어서 버튼과 정산추가 사이 공간 확보하기 (@LentoAssai )
- [x] SpaceID 길이가 길 것이므로 ...으로 잘라서 보여주기 (@LentoAssai )
- [x] 링크공유, 참석확인 색상 바꾸기 (@Asher3576 )
- [x] 참석확인을 했는 사용자라면 확인을 했다는 카드인 것임을 반영해야함 (@Asher3576 @kyustudyo )
- [x] 정산 시작 눌렀을 때 알림 메시지 스케치로 그리기 (@Asher3576 )
- [ ] 정산 시작 버튼을 눌렀을 때 "정산을 시작할까요? 수정은 안돼요" 등의 토스트 팝업 보여주기 (@kimscastle  )
- [x] 정산 시작 누른 후 프로그레싱 뷰 넣기 (Lotti~) (배민 열심히 달려가고 있어요~) (@Asher3576 )
- [ ] (나중)링크 공유 버튼을 눌렀을 때 (xx님이 "스페이스 명" 정산을 영리한 정산앱 돈워리에서 하고 싶어해요!) 등의 메시지

### CardDetailView (@kyustudyo )
- [x] CardDetailView 스케치 그리기 (@Asher3576 )
- [x] CardDetailView 다시 페이지 구성 (@kyustudyo )
- [x] 복사하기, 계좌정보 제거하기 (@kyustudyo )
- [x] 첨부사진 클릭 시 전체화면으로 보이게 하기 (@kyustudyo )
- [x] 카드 수정, 카드 삭제의 권한은 스페이스 어드민에게만 주기 (어드민에게만 수정버튼 볼 수있음, 삭제버튼은 참가자가 누르면 안된다고 알림 주기) (@kyustudyo )
- [ ] 연필 등 아이콘 추가해서 수정은 각 항목에 대해서 하기 (@kyustudyo )

### CheckAttendanceView + SpaceMainView (@kyustudyo )
- [x] 디자인 수정하기 (@Asher3576 )
- [x] 체크기능 넣은 브랜치 PR올리기 (@kyustudyo )
- [x] 체크 버튼들이 잘 안보임. 체크가 되어있다는걸 눈에 띄게 바꾸기 (Gradient) (@kimscastle )

### SpaceMainCardView (@kyustudyo )
1. 공통
- "총"이라는 단어를 대체할 수 있는 단어 생각해보기. 소계, 합계, 나온 금액, 대화식으로 "고깃집에서 xx원이 나왔어요." 등
- 인원수 자리 생각해보기
- [x] "고깃집에서 xx원이 나왔어요" 스케치 그리기 (@Asher3576 )
- [x] "고깃집에서 xx원이 나왔어요" (@kyustudyo )

2. SpaceMainView에서 사용하는 카드
- [x] 스케치 다시 그리기 (어디서 얼마가 나왔어요. n명 참가중...;;) (@Asher3576 )
- [x] 계좌번호, 복사 기능 삭제하기 (@kyustudyo )

3. AddCardDecoView에서 사용하는 카드
- 계좌정보 있어야 함.
- [x] 스케치 다시 그리기 (어디서 얼마가 나왔어요. 계좌정보 들어감) (@Asher3576 )
- [x] 복사버튼 지우기 (@kyustudyo )
- [x] n명 지우기 (@kyustudyo )

### AddCardXXXXView (@LentoAssai )
- 파베 올라가는 함수의 인자들 : SpaceID, paymentTitle, category, amount, color, date, attachedFile, taker
- [x] 변수들 바인딩으로 마지막 뷰까지 넘겨서 데이터 추가 함수 고려하기

### AddCardTitleView (@LentoAssai )
- [x] 전체적으로 조금씩 내리기 (@LentoAssai )

### AddCardIconView (@LentoAssai )
- [x] "정산 내역을 추가해볼까요?" 에서 "아이콘을 추가해볼까요?" 등의 문장으로 바꾸기 (@LentoAssai )
- [x] 스크롤 최대한 내렸을 때 다음 버튼이랑 겹치는 문제 해결하기. 투명한 프레임을 추가하는 방법? (@LentoAssai )

### AddCardPriceView (@LentoAssai )
- [x] 키패드 아래쪽에 생기는 선 지우기 (@LentoAssai )
- [x] 0원일 때 넘어가는 이슈 해결하기 (@LentoAssai )
- [x] 지우는 버튼을 SF symbols 등에서 보편적인 것으로 대체하기 (@LentoAssai )

### AddCardDecoView (@Asher3576 )
- [x] 오른쪽 상단 버튼을 홈으로 돌아가는 버튼으로 레이블 바꾸기. 돌아가기, 나가기, 유턴버튼, 취소 등의 아이디어가 있었음. (@LentoAssai )
- [x] 계좌정보가 기본적으로는 유저가 설정한 계좌정보를 불러오게 하기 (@LentoAssai )
- [ ] Date Picker 폰트 사이즈 작게하기 (@LentoAssai )

### EditProfileView (@chaneeii )
- [x] 패딩 주기 (@LentoAssai )
- [x] 확인 눌렀을 때 키보드 내리기 및 페이지 돌아가기 (@LentoAssai )

### EditAccountView (@chaneeii )
- [x] 패딩 주기 (@LentoAssai )
- [x] 확인 눌렀을 때 키보드 내리기 및 페이지 돌아가기 (@LentoAssai )

### UserInfoView (@LentoAssai )
- [x] 예금주명 대신 성명으로 텍스트 받기 (@LentoAssai )
- [x] 돈워리 타이틀 조금 띄우기 (@LentoAssai )
